package com.bw.blessclikzz;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Movie;
import android.view.View;
import android.widget.ListView;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Date;

/**
 * Created by Immanuel Raj on 2/26/2017.
 */
public class GifView extends View {

    Movie movie,movie1;
    InputStream is=null,is1=null;
    long moviestart;
    public GifView(Context context) {
        super(context);


        is=context.getResources().openRawResource(R.raw.camera4);
        movie=Movie.decodeStream(is);

    }

    @Override
    protected void onDraw(Canvas canvas) {

        canvas.drawColor(Color.WHITE);
        super.onDraw(canvas);
        long now=android.os.SystemClock.uptimeMillis();
        System.out.println("now="+now);
        if (moviestart == 0) { // first time
            moviestart = now;

        }
        System.out.println("\tmoviestart="+moviestart);
        int relTime = (int)((now - moviestart) % movie.duration()) ;
        System.out.println("time="+relTime+"\treltime="+movie.duration());
        movie.setTime(relTime);
        movie.draw(canvas,this.getWidth()/2-20,this.getHeight()/2-40);
        this.invalidate();
    }

    public static ArrayList<DataModels> GetData(){
        ArrayList<DataModel> dataModels;
        ArrayList<Comment> cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));

        dataModels= new ArrayList<>();
        dataModels.add(new DataModel(1, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-1.jpg", "Image 1", "Auth 1", "Dev-1", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(2, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-2.jpg", "Image 2", "Auth 2", "Dev-2", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(3, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 3", "Auth 3", "Dev-3", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(4, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 4", "Auth 4", "Dev-4", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(5, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-5.jpg", "Image 5", "Auth 5", "Dev-5", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(6, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-6.jpg", "Image 6", "Auth 6", "Dev-6", new Date("September 23, 2008"), cmts));
        ArrayList<DataModels> dmdls = new ArrayList<DataModels>();
        DataModels mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(7, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-7.jpg", "Image 7", "Auth 7", "Dev-7", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(8, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-8.jpg", "Image 8", "Auth 8", "Dev-8", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 7", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 8", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 9", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(9, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-9.jpg", "Image 9", "Auth 9", "Dev-9", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 10", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 12", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 13", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(10, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-10.jpg", "Image 10", "Auth 10", "Dev-10", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        dataModels= new ArrayList<>();
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 1", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 2", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 3", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(11, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-11.jpg", "Image 11", "Auth 11", "Dev-11", new Date("September 23, 2008"), cmts));
        cmts = new ArrayList<Comment>();
        cmts.add(new Comment(1, 1, "Comments 4", "Device-1", new Date("September 23, 2011")));
        cmts.add(new Comment(2, 1, "Comments 5", "Device-2", new Date("September 23, 2011")));
        cmts.add(new Comment(3, 1, "Comments 6", "Device-3", new Date("September 23, 2011")));
        dataModels.add(new DataModel(12, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-12.jpg", "Image 12", "Auth 12", "Dev-12", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(13, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-13.jpg", "Image 13", "Auth 13", "Dev-13", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(14, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-14.jpg", "Image 14", "Auth 14", "Dev-14", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(15, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-3.jpg", "Image 15", "Auth 15", "Dev-15", new Date("September 23, 2008"), cmts));
        dataModels.add(new DataModel(16, "http://immanuel.co/avez/image/catalog/demo/blazer/blazer-4.jpg", "Image 16", "Auth 16", "Dev-16", new Date("September 23, 2008"), cmts));
        mdl1 = new DataModels(dataModels);
        dmdls.add(mdl1);

        return dmdls;
    }
}